### ISSUE TITLE
Cannot start server [1.17.1]

### ISSUE THREAD

**Issue by itsdinkd** [Brian-Wuest/MC-Prefab-Fabric#24]
Latest version of mod
Tried cloth API .34 and .37

[06:38:23] [main/FATAL]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'prefab'!
        at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50) ~[fabric-server-launch.jar:?]
        at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:33) ~[fabric-server-launch.jar:?]
        at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointServer.start(EntrypointServer.java:33) ~[fabric-server-launch.jar:?]
        at net.minecraft.server.Main.main(Main.java:97) [intermediary-server.jar:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
        at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234) [fabric-server-launch.jar:?]
        at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153) [fabric-server-launch.jar:?]
        at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:28) [fabric-server-launch.jar:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
        at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:68) [fabric-server-launch.jar:?]
        at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:114) [fabric-server-launch.jar:?]
        at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:56) [fabric-server-launch.jar:?]
        Suppressed: java.lang.RuntimeException: Failed to find root directory for mod 'bclib'!
                at net.fabricmc.loader.ModContainer.obtainRootPath(ModContainer.java:74) ~[fabric-server-launch.jar:?]
                at net.fabricmc.loader.ModContainer.getRootPath(ModContainer.java:50) ~[fabric-server-launch.jar:?]
                at vazkii.patchouli.common.book.BookRegistry.findFiles(BookRegistry.java:146) ~[Patchouli-1.17-54-FABRIC.jar:?]
                at vazkii.patchouli.common.book.BookRegistry.lambda$init$2(BookRegistry.java:49) ~[Patchouli-1.17-54-FABRIC.jar:?]
                at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
                at java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1087) ~[?:?]
                at vazkii.patchouli.common.book.BookRegistry.init(BookRegistry.java:47) ~[Patchouli-1.17-54-FABRIC.jar:?]
                at vazkii.patchouli.common.base.CommonProxy.onInitialize(CommonProxy.java:25) ~[Patchouli-1.17-54-FABRIC.jar:?]
                at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-server-launch.jar:?]
                at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:33) ~[fabric-server-launch.jar:?]
                at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointServer.start(EntrypointServer.java:33) ~[fabric-server-launch.jar:?]
                at net.minecraft.server.Main.main(Main.java:97) [intermediary-server.jar:?]
                at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
                at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
                at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
                at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
                at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234) [fabric-server-launch.jar:?]
                at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153) [fabric-server-launch.jar:?]
                at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:28) [fabric-server-launch.jar:?]
                at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
                at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
                at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
                at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
                at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:68) [fabric-server-launch.jar:?]
                at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:114) [fabric-server-launch.jar:?]
                at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:56) [fabric-server-launch.jar:?]
        Caused by: java.nio.file.NoSuchFileException: /home/container/mods/bclib-0.2.4.jar
                at jdk.nio.zipfs.ZipFileSystem.<init>(ZipFileSystem.java:160) ~[jdk.zipfs:?]
                at jdk.nio.zipfs.ZipFileSystemProvider.getZipFileSystem(ZipFileSystemProvider.java:125) ~[jdk.zipfs:?]
                at jdk.nio.zipfs.ZipFileSystemProvider.newFileSystem(ZipFileSystemProvider.java:106) ~[jdk.zipfs:?]
                at java.nio.file.FileSystems.newFileSystem(FileSystems.java:338) ~[?:?]
                at java.nio.file.FileSystems.newFileSystem(FileSystems.java:287) ~[?:?]
                at net.fabricmc.loader.util.FileSystemUtil.getJarFileSystem(FileSystemUtil.java:79) ~[fabric-server-launch.jar:?]
                at net.fabricmc.loader.util.FileSystemUtil.getJarFileSystem(FileSystemUtil.java:66) ~[fabric-server-launch.jar:?]
                at net.fabricmc.loader.ModContainer.obtainRootPath(ModContainer.java:63) ~[fabric-server-launch.jar:?]
                ... 25 more
Caused by: java.lang.ExceptionInInitializerError
        at com.wuest.prefab.Prefab.onInitialize(Prefab.java:52) ~[prefab-fabric-2.1.0.jar:?]
        at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-server-launch.jar:?]
        ... 17 more
Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1922.method_8320(net.minecraft.class_2338)" because "world" is null
        at net.minecraft.class_4970$class_4971.handler$bcg000$onGetHardness(class_4970.java:3117) ~[intermediary-server.jar:?]
        at net.minecraft.class_4970$class_4971.method_26214(class_4970.java) ~[intermediary-server.jar:?]
        at com.wuest.prefab.blocks.BlockCustomWall.<init>(BlockCustomWall.java:22) ~[prefab-fabric-2.1.0.jar:?]
        at com.wuest.prefab.ModRegistry.<clinit>(ModRegistry.java:70) ~[prefab-fabric-2.1.0.jar:?]
        at com.wuest.prefab.Prefab.onInitialize(Prefab.java:52) ~[prefab-fabric-2.1.0.jar:?]
        at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-server-launch.jar:?]
        ... 17 more

**Comment by Brian-Wuest** [comment]
Works just fine with this mod list.

![image](https://user-images.githubusercontent.com/13502068/128339460-d5e0efe8-1252-4d53-b578-7ac813a16002.png)


It also looks like you are missing a mod file called "bclib" as there are error messages about that in your log output above.

**Comment by itsdinkd** [comment]
I have all those mods in your screenshot, I also have bclib in my client mods and my server mods.

![image](https://user-images.githubusercontent.com/35115304/128578949-8beb0309-5fa4-475f-b660-996c8db9aa25.png)

![image](https://user-images.githubusercontent.com/35115304/128579033-49e1b098-663b-4299-9b79-3c396d8efe08.png)


![image](https://user-images.githubusercontent.com/35115304/128578966-180c909a-c4f1-4b03-a26c-e752593ecba2.png)


**java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'prefab'!** Prefab is preventing the server to start.


I think the issue is here

Caused by: java.lang.ExceptionInInitializerError
at com.wuest.prefab.Prefab.onInitialize(Prefab.java:52) ~[prefab-fabric-2.1.0.jar:?]
at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-server-launch.jar:?]
... 17 more
Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1922.method_8320(net.minecraft.class_2338)" because "world" is null
at net.minecraft.class_4970$class_4971.handler$bcg000$onGetHardness(class_4970.java:3117) ~[intermediary-server.jar:?]
at net.minecraft.class_4970$class_4971.method_26214(class_4970.java) ~[intermediary-server.jar:?]
at com.wuest.prefab.blocks.BlockCustomWall.(BlockCustomWall.java:22) ~[prefab-fabric-2.1.0.jar:?]
at com.wuest.prefab.ModRegistry.(ModRegistry.java:70) ~[prefab-fabric-2.1.0.jar:?]
at com.wuest.prefab.Prefab.onInitialize(Prefab.java:52) ~[prefab-fabric-2.1.0.jar:?]
at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-server-launch.jar:?]

**Comment by Brian-Wuest** [comment]
So I totally blanked on that you were running this as a dedicated server and not just single player!

I won't have much time over the next few days to look at this but should after I get the code updated to use Mojang code mappings.

**Comment by Brian-Wuest** [comment]
@red2blue - I have been trying to duplicate this issue when running a dedicated server with some of the mods I saw in the error log but I haven't been able to duplicate it.

Here are the mods that seem to work with the latest available version of prefab:
![image](https://user-images.githubusercontent.com/13502068/128634930-772d65e0-4e34-4980-9ee3-bbff7b1190d9.png)

I cannot really do much at this time unless you can narrow it down to a specific mod that seems to be causing the incompatibility.

**Comment by itsdinkd** [comment]
I think its this 

"because "world" is null" 

Its not finding the world, maybe? 

I cannot really narrow it down, I have 150+ mods.

**Comment by itsdinkd** [comment]
When I put it on just the client, I can go in just fine. i can even preview structures (cannott build obviously) but the mod is working for the client side stuff. Its when it goes on the server it fails.
