### ISSUE TITLE
Error file not found

### ISSUE THREAD

**Issue by arnho72** [Brian-Wuest/MC-Prefab-Fabric#3]
Hello,

I am having a problem loading minecraft. In the logs I find this message:
```
[11:49:38] [Server thread/INFO]: This server is running CraftBukkit version 2991-Bukkit-f3f3094 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
[11:49:38] [Server thread/ERROR]: Could not load 'plugins/prefab-fabric-1.0.2.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
	at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:158) ~[craftbukkit-1.16.5.jar:2991-Bukkit-f3f3094]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:144) ~[craftbukkit-1.16.5.jar:2991-Bukkit-f3f3094]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServer.java:381) ~[craftbukkit-1.16.5.jar:2991-Bukkit-f3f3094]
	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:179) ~[craftbukkit-1.16.5.jar:2991-Bukkit-f3f3094]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:787) ~[craftbukkit-1.16.5.jar:2991-Bukkit-f3f3094]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:155) ~[craftbukkit-1.16.5.jar:2991-Bukkit-f3f3094]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.io.FileNotFoundException: Jar does not contain plugin.yml
	... 7 more
```

My version is :
CraftBukkit version 2991-Bukkit-f3f3094 (MC: 1.16.5)

The plugin is :
prefab-fabric-1.0.2.jar

After checking in the JAR the file does not exist.
Is this normal?
Thank you

**Comment by Brian-Wuest** [comment]
This mod is for the Fabric mod loader. 

Bukkit is not supported.

**Comment by arnho72** [comment]
Thanks for your quick return.

Sorry for the inconvenience :-(
