### ISSUE TITLE
Incompatible with a lot of mods

### ISSUE THREAD

**Issue by TeamRIS** [Brian-Wuest/MC-Prefab-Fabric#4]
10:59:01.332
net.minecraft.class_3503
main
Couldn't load fluid tag minecraft:water as it is missing following references: indrev:coolant_still (from Industrial Revolution),indrev:coolant_flowing (from Industrial Revolution),indrev:sulfuric_acid_still (from Industrial Revolution),indrev:sulfuric_acid_flowing (from Industrial Revolution),indrev:toxic_mud_still (from Industrial Revolution),indrev:toxic_mud_flowing (from Industrial Revolution)
10:59:01.333
net.minecraft.class_310
main
Failed to load datapacks, can't proceed with server load
java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Missing required tags: minecraft:block:minecraft:buttons,minecraft:block:minecraft:doors,minecraft:block:minecraft:fences,minecraft:block:minecraft:leaves,minecraft:block:minecraft:logs,minecraft:block:minecraft:logs_that_burn,minecraft:block:minecraft:mushroom_grow_block,minecraft:block:minecraft:planks,minecraft:block:minecraft:pressure_plates,minecraft:block:minecraft:saplings,minecraft:block:minecraft:slabs,minecraft:block:minecraft:stairs,minecraft:block:minecraft:trapdoors,minecraft:block:minecraft:wall_post_override,minecraft:block:minecraft:walls,minecraft:block:minecraft:wooden_buttons,minecraft:block:minecraft:wooden_doors,minecraft:block:minecraft:wooden_fences,minecraft:block:minecraft:wooden_pressure_plates,minecraft:block:minecraft:wooden_slabs,minecraft:block:minecraft:wooden_stairs,minecraft:block:minecraft:wooden_trapdoors,minecraft:fluid:minecraft:lava,minecraft:fluid:minecraft:water,minecraft:item:minecraft:buttons,minecraft:item:minecraft:doors,minecraft:item:minecraft:fences,minecraft:item:minecraft:leaves,minecraft:item:minecraft:logs,minecraft:item:minecraft:logs_that_burn,minecraft:item:minecraft:planks,minecraft:item:minecraft:saplings,minecraft:item:minecraft:slabs,minecraft:item:minecraft:stairs,minecraft:item:minecraft:trapdoors,minecraft:item:minecraft:wooden_buttons,minecraft:item:minecraft:wooden_doors,minecraft:item:minecraft:wooden_fences,minecraft:item:minecraft:wooden_pressure_plates,minecraft:item:minecraft:wooden_slabs,minecraft:item:minecraft:wooden_stairs,minecraft:item:minecraft:wooden_trapdoors
	at Not Enough Crashes deobfuscated stack trace.(1.16.4+build.9)
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1908)
	at net.minecraft.client.MinecraftClient.method_29604(MinecraftClient:1959)
	at net.minecraft.client.MinecraftClient.startIntegratedServer(MinecraftClient:1808)
	at net.minecraft.client.MinecraftClient.method_29608(MinecraftClient:1811)
	at net.minecraft.client.gui.screen.DatapackFailureScreen.method_29346(DatapackFailureScreen:23)
	at net.minecraft.client.gui.widget.ButtonWidget.onPress(ButtonWidget:33)
	at net.minecraft.client.gui.widget.AbstractPressableButtonWidget.onClick(AbstractPressableButtonWidget:16)
	at net.minecraft.client.gui.widget.AbstractButtonWidget.mouseClicked(AbstractButtonWidget:149)
	at net.minecraft.client.gui.ParentElement.mouseClicked(ParentElement:27)
	at net.minecraft.client.Mouse.method_1611(Mouse:92)
	at net.minecraft.client.gui.screen.Screen.wrapScreenError(Screen:435)
	at net.minecraft.client.Mouse.onMouseButton(Mouse:92)
	at net.minecraft.client.Mouse.method_22686(Mouse:162)
	at net.minecraft.util.thread.ThreadExecutor.execute(ThreadExecutor:94)
	at net.minecraft.client.Mouse.method_22684(Mouse:162)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3174)
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem:127)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1071)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:681)
	at net.minecraft.client.main.Main.main(Main:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:139)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at link.infra.jumploader.Jumploader.onLoad(Jumploader.java:171)
	at cpw.mods.modlauncher.TransformationServiceDecorator.onLoad(TransformationServiceDecorator.java:53)
	at cpw.mods.modlauncher.TransformationServicesHandler.lambda$loadTransformationServices$11(TransformationServicesHandler.java:131)
	at java.util.HashMap$Values.forEach(HashMap.java:981)
	at cpw.mods.modlauncher.TransformationServicesHandler.loadTransformationServices(TransformationServicesHandler.java:131)
	at cpw.mods.modlauncher.TransformationServicesHandler.initializeTransformationServices(TransformationServicesHandler.java:56)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:76)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
Caused by: java.lang.IllegalStateException: Missing required tags: minecraft:block:minecraft:buttons,minecraft:block:minecraft:doors,minecraft:block:minecraft:fences,minecraft:block:minecraft:leaves,minecraft:block:minecraft:logs,minecraft:block:minecraft:logs_that_burn,minecraft:block:minecraft:mushroom_grow_block,minecraft:block:minecraft:planks,minecraft:block:minecraft:pressure_plates,minecraft:block:minecraft:saplings,minecraft:block:minecraft:slabs,minecraft:block:minecraft:stairs,minecraft:block:minecraft:trapdoors,minecraft:block:minecraft:wall_post_override,minecraft:block:minecraft:walls,minecraft:block:minecraft:wooden_buttons,minecraft:block:minecraft:wooden_doors,minecraft:block:minecraft:wooden_fences,minecraft:block:minecraft:wooden_pressure_plates,minecraft:block:minecraft:wooden_slabs,minecraft:block:minecraft:wooden_stairs,minecraft:block:minecraft:wooden_trapdoors,minecraft:fluid:minecraft:lava,minecraft:fluid:minecraft:water,minecraft:item:minecraft:buttons,minecraft:item:minecraft:doors,minecraft:item:minecraft:fences,minecraft:item:minecraft:leaves,minecraft:item:minecraft:logs,minecraft:item:minecraft:logs_that_burn,minecraft:item:minecraft:planks,minecraft:item:minecraft:saplings,minecraft:item:minecraft:slabs,minecraft:item:minecraft:stairs,minecraft:item:minecraft:trapdoors,minecraft:item:minecraft:wooden_buttons,minecraft:item:minecraft:wooden_doors,minecraft:item:minecraft:wooden_fences,minecraft:item:minecraft:wooden_pressure_plates,minecraft:item:minecraft:wooden_slabs,minecraft:item:minecraft:wooden_stairs,minecraft:item:minecraft:wooden_trapdoors
	at net.minecraft.tag.TagManagerLoader.method_30224(TagManagerLoader:49)
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:670)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:646)
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:456)
	at net.minecraft.resource.ResourceReloader.method_18365(ResourceReloader:71)
	at net.minecraft.util.thread.ThreadExecutor.executeTask(ThreadExecutor:144)
	at net.minecraft.util.thread.ReentrantThreadExecutor.executeTask(ReentrantThreadExecutor:23)
	at net.minecraft.util.thread.ThreadExecutor.runTask(ThreadExecutor:118)
	at net.minecraft.util.thread.ThreadExecutor.runTasks(ThreadExecutor:127)
	at net.minecraft.client.MinecraftClient.method_29604(MinecraftClient:1958)
	... 39 more
The version of prefab: Latest
Minecraft version- 1.16.4

**Comment by Brian-Wuest** [comment]
I was able to load the game and generate a structure properly.

Game Version: 1.16.4
Mod Versions:
1. Prefab: 1.0.2
2. Industrial Revolution: 1.8.10-BETA
3. Fabric-API: 0.31.0
4. Fabric Loader: 0.11.2

I noticed mentions of "cpw.mods.modlauncher". Did you launch this from a Overwolf/Twitch installation? That app doesn't work well with Fabric installations as it's made for Forge installations.

My examples were with the standard Minecraft Launcher and mod folders.

Screen Shots:
![image](https://user-images.githubusercontent.com/13502068/108997922-d4450680-7665-11eb-88a9-9315e2f8fada.png)

![image](https://user-images.githubusercontent.com/13502068/108997975-e45ce600-7665-11eb-9688-ba9d54598dc0.png)

![image](https://user-images.githubusercontent.com/13502068/108998019-efb01180-7665-11eb-8055-e3d7ca75dd4b.png)

**Comment by TeamRIS** [comment]
This is a Overwolf install

**Comment by TeamRIS** [comment]
With jumploader

**Comment by Brian-Wuest** [comment]
Was able to start the game.

![image](https://user-images.githubusercontent.com/13502068/109295349-392e6700-77f4-11eb-95e2-21ae73f8feeb.png)

Also loaded a world
![image](https://user-images.githubusercontent.com/13502068/109295407-53684500-77f4-11eb-919f-71293c5e4b5b.png)

Here's my modlist
![image](https://user-images.githubusercontent.com/13502068/109295445-61b66100-77f4-11eb-9e24-3cbf6acb1a1e.png)

**Comment by TeamRIS** [comment]
there are other mods

**Comment by Brian-Wuest** [comment]
Please provide the full mod list so I can troubleshoot this further.

Thank you.

**Comment by Brian-Wuest** [comment]
Closing as there has been no communication in 13 days.
