### ISSUE TITLE
[Bug]: random error in console

### ISSUE THREAD

**Issue by itsdinkd** [Brian-Wuest/MC-Prefab-Fabric#43]
### Minecraft Version

1.17.1

### Fabric Version

latest

### Mod Version

latest prefab

### Details

Looking at console, I found random errors from prefab. no idea what it means, felt compelled to report though..

[02:18:05] [Server thread/FATAL] (class_1255) Error executing task on Server
 java.lang.NullPointerException: Cannot invoke "java.io.InputStream.available()" because "in" is null
        at com.google.common.io.ByteStreams.toByteArray(ByteStreams.java:165) ~[fabric-server-launch.jar:?]
        at com.wuest.prefab.ZipUtil.decompressResource(ZipUtil.java:156) ~[prefab-fabric-2.1.5.jar:?]
        at com.wuest.prefab.structures.base.Structure.CreateInstance(Structure.java:92) ~[prefab-fabric-2.1.5.jar:?]
        at com.wuest.prefab.structures.config.HouseConfiguration.ConfigurationSpecificBuildStructure(HouseConfiguration.java:179) ~[prefab-fabric-2.1.5.jar:?]
        at com.wuest.prefab.structures.config.StructureConfiguration.BuildStructure(StructureConfiguration.java:121) ~[prefab-fabric-2.1.5.jar:?]
        at com.wuest.prefab.ModRegistry.lambda$registerStructureBuilderMessageHandler$1(ModRegistry.java:383) ~[prefab-fabric-2.1.5.jar:?]
        at net.minecraft.class_3738.run(class_3738.java:18) ~[intermediary-server.jar:?]
        at net.minecraft.class_1255.redirect$gma000$redirectExecuteTask(class_1255.java:521) ~[intermediary-server.jar:?]
        at net.minecraft.class_1255.method_16075(class_1255.java:125) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:770) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:764) ~[intermediary-server.jar:?]
        at net.minecraft.class_1255.method_5383(class_1255.java:110) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:748) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.handler$dco000$modifiedRunLoop(MinecraftServer.java:9399) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:676) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270) ~[intermediary-server.jar:?]
        at java.lang.Thread.run(Thread.java:831) [?:?]
[02:18:07] [Server thread/FATAL] (class_1255) Error executing task on Server
 java.lang.NullPointerException: Cannot invoke "java.io.InputStream.available()" because "in" is null
        at com.google.common.io.ByteStreams.toByteArray(ByteStreams.java:165) ~[fabric-server-launch.jar:?]
        at com.wuest.prefab.ZipUtil.decompressResource(ZipUtil.java:156) ~[prefab-fabric-2.1.5.jar:?]
        at com.wuest.prefab.structures.base.Structure.CreateInstance(Structure.java:92) ~[prefab-fabric-2.1.5.jar:?]
        at com.wuest.prefab.structures.config.HouseConfiguration.ConfigurationSpecificBuildStructure(HouseConfiguration.java:179) ~[prefab-fabric-2.1.5.jar:?]
        at com.wuest.prefab.structures.config.StructureConfiguration.BuildStructure(StructureConfiguration.java:121) ~[prefab-fabric-2.1.5.jar:?]
        at com.wuest.prefab.ModRegistry.lambda$registerStructureBuilderMessageHandler$1(ModRegistry.java:383) ~[prefab-fabric-2.1.5.jar:?]
        at net.minecraft.class_3738.run(class_3738.java:18) ~[intermediary-server.jar:?]
        at net.minecraft.class_1255.redirect$gma000$redirectExecuteTask(class_1255.java:521) ~[intermediary-server.jar:?]
        at net.minecraft.class_1255.method_16075(class_1255.java:125) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:770) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:764) ~[intermediary-server.jar:?]
        at net.minecraft.class_1255.method_18857(class_1255.java:134) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:749) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.handler$dco000$modifiedRunLoop(MinecraftServer.java:9399) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:676) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270) ~[intermediary-server.jar:?]
        at java.lang.Thread.run(Thread.java:831) [?:?]

**Comment by Brian-Wuest** [comment]
Do you know which house you were trying to build at the time from the Starting house item?

**Comment by itsdinkd** [comment]
I've no idea. I randomly saw it in console after a player joined.

**Comment by Brian-Wuest** [comment]
Figured out that this was an issue with building the "Sub-Aquatic" house.
