### ISSUE TITLE
[Bug]: Game Crashes on launch

### ISSUE THREAD

**Issue by KawaiiUzi** [Brian-Wuest/MC-Prefab-Fabric#60]
### Minecraft Version

1.18.2

### Fabric Version

0.13.3

### Mod Version

3.1.0

### Details

Game was launching then it crashes when trying to load up, i look at my crash reports but for some reason it don't register as a crash for some reason. I could tell it was prefab tho. not sure what would be causing this issue sense i got everything needed for this to work. maybe something conflicting with it? here is my mod list so far. 
________________________________
        - amplified-nether 1.1
	- animal_feeding_trough 1.0.3+1.18.2
	- architectury 4.0.25
	- autoconfig1u 3.4.0
	- betterf3 1.2.3
	- charm 4.0.0
	- charmonium 4.0.0
	- cloth-api 3.2.64
	- croptopia 1.8.1
	- customsplashscreen 1.2.0
	- disenchanter 0.1.5+1.18
	- fabric 0.47.8+1.18.2
	- fabricloader 0.13.3
	- fallingleaves 1.10.0+1.18.2
	- geckolib3 3.0.35
	- goosik-config 0.2.0 via visuality
	- iris 1.2.1-rc1-d088e80e-dirty
	- logical_zoom 0.0.14
	- minecraft 1.18.2
	- modmenu 3.0.1
	- physicsmod 2.6.7
	- roughlyenoughitems 8.0.438
	- seedfix 1.0.1
	- sodium 0.4.0-alpha6+rev.7bd2b7d
	- starlight 1.0.2+fabric.89b8d9f
	- visuality 0.4.2
	- wthit 4.7.0
	- xaerominimap 22.3.0
	- xaeroworldmap 1.20.3.1

**Comment by Brian-Wuest** [comment]
Great....so this error doesn't appear in development environments. It only appears when running the full game so I have no idea how to fix this right now as it's going to take a lot of troubleshooting.

Going to take the version off of curseforge until I get this looked at.


For Reference; here is the logged error I am getting


[12:32:36] [Render thread/ERROR]: Unhandled game exception
java.lang.IllegalStateException: Some intrusive holders were not added to registry: [Reference{null=Block{minecraft:air}}]
	at net.minecraft.class_2370.method_40276(class_2370.java:330) ~[client-intermediary.jar:?]
	at net.minecraft.class_2378.method_40292(class_2378.java:369) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.handler$zfa001$onStart(class_310.java:4984) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:716) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:236) [client-intermediary.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416) [fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.13.3.jar:?]
[12:32:37] [Render thread/INFO]: Stopping!
[12:32:39] [Render thread/ERROR]: Shutdown failure!
java.util.ConcurrentModificationException: null
	at java.util.HashMap.forEach(HashMap.java:1424) ~[?:?]
	at net.minecraft.class_1060.close(class_1060.java:173) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.close(class_310.java:1048) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1490(class_310.java:1026) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:252) [client-intermediary.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416) [fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.13.3.jar:?]

**Comment by KawaiiUzi** [comment]
Alright, All good take your time and make it perfect! Love the mod.

**Comment by Brian-Wuest** [comment]
Got this fixed for 3.1.1, thanks for finding this. Finally figured out that I missed registering an item.

**Comment by KawaiiUzi** [comment]
Alright sweet! thanks for updating !
