### ISSUE TITLE
[Bug]: Invalid Player Data when removing startinghouse

### ISSUE THREAD

**Issue by itsdinkd** [Brian-Wuest/MC-Prefab-Fabric#64]
### Minecraft Version

1.18.2

### Fabric Version

0.51.1

### Mod Version

3.1.5

### Details

When you remove the value for StartingItem in the config, "StartingHouse" and you just make it a quote, when you start the game, this line gets removed from the config. When you join a single player world, or even a server, you get invalid player config.

If this is not how you remove the starting house, what is the proper way to do this? There is no "true/false" entry".

```java
[19:15:04] [Server thread/ERROR]: Couldn't place player in world
java.lang.NullPointerException: Cannot invoke "com.wuest.prefab.config.ModConfiguration$StartingItemOptions.toString()" because "this.startingItem" is null
	at Not Enough Crashes deobfuscated stack trace.(1.18.2+build.3) ~[?:?]
	at com.wuest.prefab.config.ModConfiguration.writeCompoundTag(ModConfiguration.java:59) ~[prefab-fabric-3.1.5.jar:?]
	at com.wuest.prefab.events.ServerEvents.lambda$playerJoinedServer$1(ServerEvents.java:52) ~[prefab-fabric-3.1.5.jar:?]
	at net.fabricmc.fabric.api.event.lifecycle.v1.ServerEntityEvents.lambda$static$0(ServerEntityEvents.java:42) ~[fabric-lifecycle-events-v1-2.0.3+2d83e92c60-9b014c802997cc2d.jar:?]
	at net.minecraft.server.world.ServerWorld$ServerEntityHandler.handler$fgh000$invokeEntityLoadEvent(ServerWorld:1635) ~[?:?]
	at net.minecraft.server.world.ServerWorld$ServerEntityHandler.startTracking(ServerWorld:1519) ~[?:?]
	at net.minecraft.server.world.ServerWorld$ServerEntityHandler.startTracking(ServerWorld:1480) ~[?:?]
	at net.minecraft.server.world.ServerEntityManager.startTracking(ServerEntityManager:210) ~[?:?]
	at net.minecraft.server.world.ServerEntityManager.addEntity(ServerEntityManager:180) ~[?:?]
	at net.minecraft.server.world.ServerEntityManager.addEntity(ServerEntityManager:161) ~[?:?]
	at net.minecraft.server.world.ServerWorld.addPlayer(ServerWorld:846) ~[?:?]
	at net.minecraft.server.world.ServerWorld.onPlayerConnected(ServerWorld:832) ~[?:?]
	at net.minecraft.server.PlayerManager.onPlayerConnect(PlayerManager:233) ~[?:?]
	at net.minecraft.server.network.ServerLoginNetworkHandler.addToServer(ServerLoginNetworkHandler:130) ~[?:?]
	at net.minecraft.server.network.ServerLoginNetworkHandler.acceptPlayer(ServerLoginNetworkHandler:117) ~[?:?]
	at net.minecraft.server.network.ServerLoginNetworkHandler.redirect$fhk000$handlePlayerJoin(ServerLoginNetworkHandler:563) ~[?:?]
	at net.minecraft.server.network.ServerLoginNetworkHandler.tick(ServerLoginNetworkHandler:67) ~[?:?]
	at net.minecraft.network.ClientConnection.tick(ClientConnection:243) ~[?:?]
	at net.minecraft.server.ServerNetworkIo.tick(ServerNetworkIo:183) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickWorlds(MinecraftServer:918) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer:851) ~[client-intermediary.jar:?]
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer:97) ~[?:?]
	at net.minecraft.server.MinecraftServer.handler$chk000$modifiedRunLoop(MinecraftServer:5396) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer:676) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer:273) ~[client-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]

**Comment by Brian-Wuest** [comment]
The comment says it right there for you. It's the word nothing.....

**Comment by itsdinkd** [comment]
> The comment says it right there for you. It's the word nothing.....

What comment????

**Comment by itsdinkd** [comment]
There is no comment?

![image](https://user-images.githubusercontent.com/35115304/167269462-88f4a913-cc80-47ba-96be-9a1b7e2b966f.png)

**Comment by Brian-Wuest** [comment]
Oh...well color me embarrassed...I thought there was!

Sorry for the snarky response! I must be thinking of the forge configuration.

In the field write the word "Nothing" instead of what is currently there ("StartingHouse").

Capitalization is important.

I will have the wiki updated to make sure this is known.

**Comment by itsdinkd** [comment]
It's alright, we all have our moments. Thanks, I'll swap the value

**Comment by itsdinkd** [comment]
wanted to give a heads up on this that there are still no comments in the config just in case other people come across this issue
